// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 819426ab18
// Version Date: 2020-10-16T09:15:44Z

package main

import (
	"flag"

	// This Service
	"github.com/Reasno/jumpstart/app-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
